# permissions for end users to view rayservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rayservice-viewer-role
rules:
- apiGroups:
  - rayservice.io
  resources:
  - rayservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rayservice.io
  resources:
  - rayservices/status
  verbs:
  - get
